### ISSUE TITLE
12--Are You Ready For Some SQL?--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#104]
#### Tasks
* [X] {S} Create a new Issue with these tasks!
* [X] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your `TIY-Assignments` repo.
    * [x] Create the files and directories as described in _Deliverables_.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [X] {M} Complete the MSSQLCommand tutorial
* [x] {L} Complete first 13 lessons of the Learn SQL the Hard Way tutorial
* [x] {L} Complete the nine select statements In the deliverables.
* [ ] {M} Read the following Rails Guides:
  * [ ] Active Record Basics](http://guides.rubyonrails.org/active_record_basics.html)
  * [ ] Active Record Associations, Section 1-2.3](http://guides.rubyonrails.org/association_basics.html)
  * [ ] Active Record Querying](http://guides.rubyonrails.org/active_record_querying.html)
* [x] {S} End of day wiki edit **(please do these as your final tasks)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ] {S} Complete assignments with 2 thumbs up.

**Comment by Peterortiz82** [comment]
[WIKI PAGES](https://github.com/Peterortiz82/TIY-Assignments/wiki)
