### ISSUE TITLE
12 -- Are You Ready For Some SQL? -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#106]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)***
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Complete the MSSQLCommand tutorial ***(S)***
* [ ] Complete first 13 lessons of the Learn SQL the Hard Way tutorial ***(L)***
* [ ] Read the following Rails Guides: ***(M)***
  * [ ] Active Record Basics
  * [ ] Active Record Associations, Section 1-2.3
  * [ ] Active Record Querying
* [ ] a `/sql` directory with any sql files you created for "Learn the Hard Way" ***(L)***
* [ ] a separate file listing the queries you wrote for that tutorial (saved under the name `learn_the_hard_way_queries.sql`) ***(L)***
* [ ] The queries you need to write in the sqlite console to work out the following selects (saved as `nfl_queries.sql`): ***(L)***
  * [ ] Select every team from the NFC North
  * [ ] Select every team with at least 11 wins
  * [ ] Select every team with at least 8 wins that did not make the playoffs
  * [ ] Rename every team with fewer than 4 wins "Losers"
  * [ ] Select every team that plays in a city of fewer than 5 million people, and the name of the city
  * [ ] Select every AFC team that plays in a city that is shrinking in population
  * [ ] Select every city that has a team
  * [ ] Select every state that has a team
  * [ ] Select every team that plays in California

**Comment by angelabier1** [comment]
[Pull Request](https://github.com/angelabier1/TIY-Assignments/pull/16 )

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki
