### ISSUE TITLE
12--Are-You-Ready-For-Some-SQL? - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#108]
**Tasks**

- [x] A WIP Issue in the class repo titled "12 -- Are You Ready For Some SQL?" (m)
    - [x] Estimates for the top-level checkboxes (xs)
- [ ] Update your TIY-Assignments repo wiki: (s)
    - [ ] Add your thoughts on today's assignment to the existing reflections page
    - [ ] Edit the lightbulbs and struggles pages
- [x] A branch named feature/12 -- Are You Ready For Some SQL? (M)
- [ ] Tasks
    - [x] Complete the MSSQLCommand tutorial
    - [ ] Complete first 13 lessons of the Learn SQL the Hard Way tutorial
    - [ ] Complete the nine select statements for NLF sql
    - [ ] Read the following Rails Guides:
        - [ ] Active Record Basics
        - [ ] Active Record Associations, Section 1-2.3
        - [ ] Active Record Querying
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] description that links to your WIP Issue in the class repo using Github Flavored Markdown (S)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored Markdown
- [ ] a link to your PR using Github Flavored Markdown12 -- Are You Ready For Some SQL?

**Comment by QueVee** [comment]
https://github.com/QueVee/TIY-Assignments/wiki
