### ISSUE TITLE
13--Active Record - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#110]
**Tasks**

- [x] A WIP Issue in the class repo titled "13 -- Active Record" (m)
    - [x] Estimates for the top-level checkboxes (xs)
- [ ] Update your TIY-Assignments repo wiki: (s)
    - [ ] Add your thoughts on today's assignment to the existing reflections page
    - [ ] Edit the lightbulbs and struggles pages
- [ ] A branch named feature/13--Active Record (M)
- [ ] Tasks (XXXL)
    - [ ] Complete the nine select statements for NFL sql
    - [ ] Complete the nine select statements for NFL rails
    - [ ] Additional NFL queries
    - [ ] Rails queries
    - [ ] Method writing time
    - [ ] Read the following Rails Guides:
        - [ ] Active Record Basics
        - [ ] Active Record Associations, Section 1-2.3
        - [ ] Active Record Querying
        - [ ] Active Record Validations
        - [ ] Active Record Migrations
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] description that links to your WIP Issue in the class repo using Github Flavored Markdown (S)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored Markdown
- [ ] a link to your PR using Github Flavored Markdown 13-- ActiveRecord

**Comment by QueVee** [comment]
https://github.com/QueVee/TIY-Assignments/wiki
