### ISSUE TITLE
13 -- ActiveRecord -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#114]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
  * [ ] End of Day: 
	   * [ ] Assignment Evaluation
	   * [ ] Lightbulbs
	   * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [x] The queries you need to write in the Rails console to work out the following selects (saved as active`nfl_queries.rb`): ***(L)***
  * [x] Select every team from the NFC North
  * [x] Select every team with at least 11 wins
  * [x] Select every team with at least 8 wins that did not make the playoffs
  * [x] Rename every team with fewer than 4 wins "Losers"
  * [x] Select every team that plays in a city of fewer than 5 million people, and the name of the city
  * [x] Select every AFC team that plays in a city that is shrinking in population
  * [x] Select every city that has a team
  * [x] Select every state that has a team
  * [x] Select every team that plays in California
  * [x] Find the 3 smallest cities with NFL teams
  * [x] Find the number of teams in cities of between 1 million and 2 million (as of 2013)
  * [x] Find the division with the largest average number of wins
  * [x] List the names of the teams of the AFC in descending order of the size of their cities
  * [x] Change the name of the 5th largest city in New Jersey to include the phrase "like the inventor"
  * [x] Remove New Mexico and all its cities from the database with one line in the console. You can edit a line in file in app/models too.
* [ ] Try to get the effect of each of these in the console, and once you have something that works, write a method in the appropriate place. ***(L)***
    * [ ] `city.rb` file with the following methods:
      * [ ] Define a method City.fastest_growing that returns the single fastest growing city
      * [ ] Define a method City.shrinking that returns all cities with decreasing population
    * [ ] `team.rb` file with the following methods:
      * [ ] Define a method Team#division_rivals that returns all other teams in the same (conference and) division
      * [ ] Define a method Team#division_leader? that checks whether a team has more wins than any other team in its (conference and) division
      * [ ] Define a method Team#division_winner? that checks whether a team leads its division and all its division rivals have played 16 games.
* [x] Read the following Rails Guides: ***(M)***
  * [x] Active Record Basics
  * [x] Active Record Associations, Section 1-2.3
  * [x] Active Record Querying
  * [ ] Active Record Validations
  * [ ] Active Record Migrations

**Comment by angelabier1** [comment]
[Pull Request](https://github.com/angelabier1/TIY-Assignments/pull/17 )

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki
