### ISSUE TITLE
13 -- ActiveRecord - Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#116]
#### Tasks
* [X] {S} Create a new Issue with these tasks!
* [X] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [ ] {S} Use the Terminal in your computer to:
    * [ ] create a W.I.P branch of your `TIY-Assignments` repo.
    * [ ] Create the files and directories as described in _Deliverables_.
    * [ ] Add and commit your work.
    * [ ] Push your commits to Github.
    * [ ] In Github, open a PR.
* [ ] {XL} NFL queries in Rails console (nfl_queries.rb)
    * [x] Select every team from the NFC North
    * [x] Select every team with at least 11 wins
    * [x] Select every team with at least 8 wins that did not make the playoffs
    * [ ] Rename every team with fewer than 4 wins "Losers"
    * [x] Select every team that plays in a city of fewer than 5 million people, and the name of the city
    * [ ] Select every AFC team that plays in a city that is shrinking in population
    * [ ] Select every city that has a team
    * [ ] Select every state that has a team
    * [ ] Select every team that plays in California
    * [ ] Find the 3 smallest cities with NFL teams
    * [ ] Find the number of teams in cities of between 1 million and 2 million (as of 2013)
    * [ ] Find the division with the largest average number of wins
    * [ ] List the names of the teams of the AFC in descending order of the size of their cities
    * [ ] Change the name of the 5th largest city in New Jersey to include the phrase "like the inventor"
    * [ ] Remove New Mexico and all its cities from the database with one line in the console. You can edit     a line in file in app/models too.
* [ ] {XL} Next, method writing time. Try to get the effect of each of these in the console, and once you have something that works, write a method in the appropriate place. It's not the formalized testing we've been doing, but you'll see that again soon. (city.rb and team.rb) (L)
    * [ ] Define a method City.fastest_growing that returns the single fastest growing city
    * [ ] Define a method City.shrinking that returns all cities with decreasing population
    * [ ] Define a method Team#division_rivals that returns all other teams in the same (conference and) division
    * [ ] Define a method Team#division_leader? that checks whether a team has more wins than any other team in its (conference and) division
    * [ ] Define a method Team#division_winner? that checks whether a team leads its division and all its division rivals have played 16 games
* [ ] {S} End of day wiki edit **(please do these as your final tasks)**
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ] Complete code assignments with 2 thumbs up.
