### ISSUE TITLE
14 -- ActiveRecord-2 -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#119]
#### Tasks
* [x] {S} Create a new Issue with these tasks!
* [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your `TIY-Assignments` repo.
    * [x] Create the files and directories as described in _Deliverables_.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {XL}Complete code assignment
    * [x] Create a Coach class and a migration for it.
    * [x] Create a Game class and a migration for it
    * [x] Add coaches for every team that made the playoffs
    * [ ] Define Team#won
    * [ ] Define Team#opponents
    * [ ] Define Coach#beat
    * [ ] Add validations for each class as appropriate.
    * [ ] Another step in the HTML document: take step_2.html and make it look like step_2_after.png
* [ ] {M] Read the following Rails Guides:
  * [ ] [Active Record Basics](http://guides.rubyonrails.org/active_record_basics.html)
  * [ ] [Active Record Associations, Section 1-2.3](http://guides.rubyonrails.org/association_basics.html)
  * [ ] [Active Record Querying](http://guides.rubyonrails.org/active_record_querying.html)
  * [ ] [Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html)
  * [ ] [Active Record Migrations](http://guides.rubyonrails.org/active_record_migrations.html)
* [ ] {S} End of day wiki edit 
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.

**Comment by Peterortiz82** [comment]
[Wiki Pages](https://github.com/Peterortiz82/TIY-Assignments/wiki)
