### ISSUE TITLE
14 -- ActiveRecord-2 -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#120]
# Tasks 

* [ ] Extend the data model
   * [ ] Create a Coach class and a migration for it, The coach should have a name and a team.
   * [ ] Create a Game class and a migration for it which should include a date, a home team, an away team, and scores for each.
   * [ ] Add coaches for every team that made the playoffs, every game for the last week of the regular season, and every game for one specific team.
   * [ ] Define Team#won? which should say whether a team won a particular game and test it against the data you entered.
   * [ ] Define Team#opponents, which should return every team a team played during the season.
   * [ ] Define Coach#beat?, which should say whether a coach beat another team. Extend the method to be able to say whether a coach beat another team, or whether a coach beat another coach.
   * [ ] Add validations for each class as appropriate. (You'll have to read up on what kind of validations are available.) Attempt to create an object that should fail the validation to ensure the validation is structured correctly.
   * [ ] Another step in the HTML document: take step_2.html and make it look like step_2_after.png
* [ ] turn the following in, within a new branch off of master, in a folder called `active_record-2`
   * [ ] `city.rb` and `state.rb` files with appropriate validations
   * [ ] `team.rb`, `coach.rb`, and `game.rb` files with appropriate validations and methods as described above
   * [ ] `step_2.html`

* [ ] Read the following Rails Guides:
  * [ ] [Active Record Basics](http://guides.rubyonrails.org/active_record_basics.html)
  * [ ] [Active Record Associations, Section 1-2.3](http://guides.rubyonrails.org/association_basics.html)
  * [ ] [Active Record Querying](http://guides.rubyonrails.org/active_record_querying.html)
  * [ ] [Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html)
  * [ ] [Active Record Migrations](http://guides.rubyonrails.org/active_record_migrations.html)
* [x] A WIP Issue in the class repo (S)
   * [x] Titled appropriately
   * [x] With check boxes for the tasks and any subtasks you can identify
   * [x] Estimates for the top-level checkboxes
* [x] Update your `TIY-Assignments` wiki (S)
   * [x] End of Lab (Due by 5 pm):
      * [x] Assignment Evaluation
      * [x] Lightbulbs
      * [x] Things I Don’t Get Yet
* [x] Create a branch in your `TIY-Assignments` repo, named appropriately (S)
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments (S)
* [ ] Comments on your WIP Issue as on previous assignments (S)
   * [ ] Link to Wiki
   * [ ] Link to Pull Request (in Markdown)
