### ISSUE TITLE
14 -- ActiveRecord-2

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#121]
**Tasks**

- [x] A WIP Issue in the class repo titled "14 -- ActiveRecord-2" (m)
    - [x] Estimates for the top-level checkboxes (xs)
- [ ] Update your TIY-Assignments repo wiki: (s)
    - [ ] Add your thoughts on today's assignment to the existing reflections page
    - [ ] Edit the lightbulbs and struggles pages
- [ ] A branch named feature/14--ActiveRecord-2 (M)
- [ ] Tasks (XXXL)
    - [ ] Create Coach class and migration for it. Should have name and team
    - [ ] Create a Game class and a migration for it. A game should have a date, a home team, an away
        team, and scores for each.
    - [ ] Add coaches for every team that made the playoffs
    - [ ] every game for the last week of the regular season,
    - [ ] every game for one specific team
    - [ ] Define Team#won? which should say whether a team won a particular game. Test it against the
        data you entered.
    - [ ] Define Team#opponents, which should return every team a team played during the season
    - [ ] Define Coach#beat?, which should say whether a coach beat another team. Extend the method to
        be able to say whether a coach beat another team, or whether a coach beat another coach.
    - [ ] Add validations for each class as appropriate. Attempt to create an object that should fail the
        validation to ensure the validation is structured correctly.
    - [ ] HTML document: take step_2.html and make it look like step_2_after.png
    - [ ] Read the following Rails Guides:
        - [x] Active Record Basics
        - [x] Active Record Associations, Section 1-2.3
        - [x] Active Record Querying
        - [ ] Active Record Validations
        - [ ] Active Record Migrations
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] description that links to your WIP Issue in the class repo using Github Flavored Markdown (S)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored MarkdownDescription
