### ISSUE TITLE
14 -- ActiveRecord-2 - J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#122]
#### **Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)***
  * [ ] End of Lab *(Due by 5 pm)*: 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
  * [ ] End of Day: 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Create Coach class and a migration for it ***(M)***
  * [ ] The coach should have a name and a team.
* [ ] Create a Game class and a migration for it. ***(M)***
  * [ ] A game should have a date, a home team, an away team, and scores for each.
* [ ] Next Steps ***(XL)***
  * [ ] Add coaches for every team that made the playoffs, every game for the last week of the regular season, and every game for one specific team. (Either your favorite or not the Patriots.)
  * [ ] Define Team#won? which should say whether a team won a particular game. Test it against the data you entered. 
  * [ ] Define Team#opponents, which should return every team a team played during the season.
  * [ ] Define Coach#beat?, which should say whether a coach beat another team. Extend the method to be able to say whether a coach beat another team, or whether a coach beat another coach.
  * [ ] Add validations for each class as appropriate. (You'll have to read up on what kind of validations are available.) Attempt to create an object that should fail the validation to ensure the validation is structured correctly.
  * [ ] Another step in the HTML document: take step_2.html and make it look like step_2_after.png

**Comment by jspencerhopkins** [comment]
[Wikis](https://github.com/jspencerhopkins/TIY-Assignments/wiki)
