### ISSUE TITLE
14 -- ActiveRecord-2--Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#124]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
  * [ ] End of Day: 
	   * [ ] Assignment Evaluation
	   * [ ] Lightbulbs
	   * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Extend the data model: ***(XXL)***
  * [ ] Create a Coach class and a migration for it. The coach should have:
      * [ ] a name
      * [ ] a team
  * [ ] Create a Game class and a migration for it. A game should have:
    * [ ] a date
    * [ ] home team
    * [ ] away team
    * [ ] scores for each
  * [ ] Add Coaches for:
    * [ ] Every team that made the playoffs
    * [ ] Every game for the last week of the regular season
    * [ ] Every game for one specific team. (Either your favorite or not the Patriots.)
  * [ ] Define & Test Team#won?
  * [ ] Define Team#opponents
  * [ ] Define Coach#beat?
    * [ ] Extend the method to be able to say whether a coach beat another team, or whether a coach beat another coach.
  * [ ] Add validations for each class as appropriate.
    * [ ] Attempt to create an object that should fail the validation to ensure the validation is structured correctly.
  * [ ] Take step_2.html and make it look like step_2_after.png
* [ ] Folder called `active_records`: ***(S)***
  * [ ] `city.rb` and `state.rb`
  * [ ] `team.rb`, `coach.rb`, and `game.rb`
  * [ ] `step_2.html`
* [ ] Read the following Rails Guides: ***(S)***
  * [ ] Active Record Basics
  * [ ] Active Record Associations, Section 1-2.3
  * [ ] Active Record Querying
  * [ ] Active Record Validations
  * [ ] Active Record Migrations

**Comment by angelabier1** [comment]
[Pull Request](https://github.com/angelabier1/TIY-Assignments/pull/18 )

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki
