### ISSUE TITLE
15 -- Sup-ERB-owl (except without ERB really) -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#126]
#### Tasks
* [x] {S} Create a new Issue with these tasks!
* [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P of your new repo.
    * [x] Create the files and directories as described in _Deliverables_.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {XL} Finish weekend project
    * [ ] Create users (100 users) that can make predictions.
    * [ ] Update games table to include point spread.
    * [x] Use Sports Data Api to add data for every 2014 NFL game
    * [ ] Update coaches wins and losses.
    * [ ] Rank users based on who had the highest winning predictions.
* [x] {S} End of day wiki edit 
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.
