### ISSUE TITLE
15 -- Sup-ERB-owl (except without ERB really) - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#127]
15 -- Sup-ERB-owl (except without ERB really)
**Tasks**

- [x] A WIP Issue in the class repo titled "15 -- Sup-ERB-owl " (m)
    - [x] Estimates for the top-level checkboxes (xs)
- [x] Update your TIY-Assignments repo wiki: (s)
    - [x] Add your thoughts on today's assignment to the existing reflections page
    - [x] Edit the lightbulbs and struggles pages
- [ ] A branch named 15 -- Sup-ERB-owl  (M)
- [ ] Tasks (XXXL)
    - [ ] The app should have users who can make predictions about the final scores of upcoming games.
    - [ ] The games table should be updated to include point spreads.
    - [ ] It should be possible to rank users by how successful they were at picking winners as well as how successful they were at beating the spread.
    - [ ] It should also be possible to rank teams based on their records as well as how successful they were at beating the spread.
    - [ ] Use the Sports Data API to add data on every game from the 2014 NFL regular season into your database. 
    - [ ] Since there's a coaches table now, they should have wins and losses too.
    - [ ] Look into Active Record Callbacks to see how to update a coach's wins and losses each time his team wins or loses a game.
    - [ ] Use the .csv file Spencer posted on HipChat to generate point spreads for the first few weeks of the season. After that, use random numbers.
    - [ ] Make up 100 users,
    - [ ] Get the app into Git
    - [ ] In your PR, link to the new repository instead of your TIY-Assignments one.
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored MarkdownDescriptionDescription

This is going to be super. :)
