### ISSUE TITLE
15 -- Sup-ERB-owl -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#131]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
  * [ ] End of Day: 
	   * [ ] Assignment Evaluation
	   * [ ] Lightbulbs
	   * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Use the Sports Data API to add data on every game from the 2014 NFL regular season into your database. ***(XL)***
* [ ] Since there's a coaches table now, they should have wins and losses too.  ***(L)***
* [ ] Use Spencer's point spread csv to add point spreads to the games table ***(XL)***
* [ ] Create 100 users ***(L)***
* [ ] It should be possible to rank users by how successful they were at picking winners as well as how successful they were at beating the spread. ***(L)***
* [ ] It should also be possible to rank teams based on their records as well as how successful they were at beating the spread. ***(L)***
