### ISSUE TITLE
16--Reading-Routing-Rails --Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#132]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] The first thing I want you to do is read the documentation.  ***(M)***
  * [ ] The First One
    * [ ] Build out the app they talk about here too
  * [ ] Routing 1.1-2.2
  * [ ] Action Controller 1-3
  * [ ] Layouts and Rendering (aka views)
* [ ] Set up some routes in the football app ***(M)***
  * [ ] Make a home page in its own controller, with a nice header and a description of what the app is for, and a link to the URL "/teams".
  * [ ] Hook that URL up to an action called #index in an appropriately named controller.
  * [ ] The index page should list all of the teams.  
  * [ ] Each item in the list should contain a link to a page for that team.
* [ ] Style the site so the colors &c match step_\2_after.png in the /html folder in here. Add a football-themed banner image for the home page. ***(S)***

**Comment by angelabier1** [comment]
https://github.com/angelabier1/Rails_projects/wiki
