### ISSUE TITLE
15--3-Rs-Reading, Routing, Rails--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#136]
#### Tasks
* [X] {S} Create a new Issue with these tasks!
* [X] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [X] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your `TIY-Assignments` repo.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {M} READ the documentation.
   * [x] [The First One](http://guides.rubyonrails.org/getting_started.html)
   * [x] Build out the app they talk about here too
   * [x] [Routing](http://guides.rubyonrails.org/routing.html) 1.1-2.2
   * [ ] [Action Controller](http://guides.rubyonrails.org/action_controller_overview.html) 1-3
   * [ ] [Layouts and Rendering (aka views)](http://guides.rubyonrails.org/layouts_and_rendering.html)
* [ ] {L} Setup routes in Football app
    * [x] Make a home page in its own controller
    * [x] Add a header and a description of what the app is for.
    * [ ] Setup index in controller
    * [ ] List all of the teams on the index page.
* [ ] {S} Style the site.
* [X] {S} End of day wiki edit 
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [X]  {S} 2 thumbs up.
