### ISSUE TITLE
16--Reading, Routing, Rails - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#137]
**Tasks**

- [x] A WIP Issue in the class repo titled "16--Reading, Routing, Rails " (m)
    - [x] Estimates for the top-level checkboxes (xs)
- [ ] Update your TIY-Assignments repo wiki: (s)
    - [ ] Add your thoughts on today's assignment to the existing reflections page
    - [ ] Edit the lightbulbs and struggles pages
- [x] A branch named 16--Reading, Routing, Rails  (M)
- [ ] Tasks (XXXL)
    - [ ] Read:
        - [ ] The First One
        - [ ] Routing 1.1-2.2
        - [ ] Action Controller 1-3
        - [ ] Layouts and Rendering (aka views)
    - [ ] The second thing is to set up some routes in the football app. 
    - [ ] The second thing is to set up some routes in the football app. 
    - [ ] Make a home page in its own controller.
    - [ ] The index page should list all of the teams.
    - [ ] Style the site 
    - [ ] In your PR, link to the new repository instead of your TIY-Assignments one.
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored MarkdownDescriptionDescription

**Comment by QueVee** [comment]
https://github.com/QueVee/Rails_Project/wiki

**Comment by QueVee** [comment]
https://github.com/QueVee/Rails_Project/pull/2
