### ISSUE TITLE
15 -- 3 Rs - Reading, Routing, Rails -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#138]
# Task

* [ ] The first thing I want you to do is read the documentation. It won't all stick, but read it anyway. Specifically, read these sections of the guides: (M)
   * [ ] [The First One](http://guides.rubyonrails.org/getting_started.html) (S)
      * [ ] Build out the app they talk about here too (M)
   * [ ] [Routing](http://guides.rubyonrails.org/routing.html) 1.1-2.2 (S)
   * [ ] [Action Controller](http://guides.rubyonrails.org/action_controller_overview.html) 1-3 (S)
   * [ ] [Layouts and Rendering (aka views)](http://guides.rubyonrails.org/layouts_and_rendering.html) (S)
* [ ] The second thing is to set up some routes in the football app (M)
   * [ ] Make a home page in its own controller, with a nice header and a description of what the app is for, and a link to the URL `"/teams"` (M)
   * [ ] Hook that URL up to an action called `#index` in an appropriately named controller (M)
      * [ ] The index page should list all of the teams (L)
   * [ ] Each item in the list should contain a link to a page for that team (M)
      * [ ] So you'll need to have routes for all teams together, and one team by itself, each with matching controller actions and view files (L)
   * [ ] There's a concept in Rails routing called "resources" which could make part of that easier. It's in the documentation. Feel free to refer back to it while you're working (M)
* [ ] Style the site so the colors &c match step_\2_after.png in the /html folder in here. Add a football-themed banner image for the home page (M)

* [ ] Update wiki afterwards (S)
