### ISSUE TITLE
17--Yelp-But-Not-of-Pain -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#140]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `Rails_projects` wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `Rails_projects` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `Rails_projects` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Create a Restaurant Review Site with:***(L)***
  * [ ] Restaurants
  * [ ] Users
  * [ ] Reviews of Restaurants posted by (or at least attributed to) users
