### ISSUE TITLE
17 -- Yelp, But Not of Pain -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#143]
# Task
* [ ] A functioning, if probably ugly, restaurant review site, with restaurants, users, and reviews of restaurants posted by (or at least attributed to) users. (XL)
   * [ ] Add a review resource, so that a review can be posted by a user (You'll need users too.) (M)
   * [ ] We haven't done anything on logging in users, so you can either go completely insane and figure out authentication on your own by tomorrow OR you can put a select box in the review form and select the user for the review that way. It's a hack. (M)
   * [ ] Make the restaurant page show its reviews, and put the form to add a review on that same page
   * [ ] Format the reviews to display nicely in a list under the restaurant information
* [ ] Update your wiki afterwards
