### ISSUE TITLE
17--Yelp, But Not of Pain--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#144]
#### Tasks
* [X] {S} Create a new Issue with these tasks!
* [X] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [X] {S} Use the Terminal in your computer to:
    * [X] create a new repo.
    * [X] Add and commit your work.
    * [X] Push your commits to Github.
    * [X] In Github, open a PR.
* [ ] {XL} Finish code assignment.
    * [ ] Add a review resource
    * [ ] Create users who can leave reviews
    * [ ] Make the restaurant page show its reviews, and put the form to add a review on that same page.
    * [ ] Format the reviews to display nicely in a list under the restaurant information.
* [ ] {S} End of day wiki edit 
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.
