### ISSUE TITLE
18 -- HTML Tag, You're It - J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#146]
#### **Tasks**

* [x] A _WIP Issue_ in the class repo ***(S)***
  * [x] Titled appropriately
  * [x] With check boxes for the tasks *and any subtasks you can identify*
  * [x] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)***
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Reading Material ***(XL)***
  * [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms_in_HTML
  * [ ] https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Forms
  * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Element
  * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
* [ ] Tidy up views in restaurant review app ***(L)***
  * [ ] Wrap all the tags inside each form in a `fieldset` tag, and add a `legend` to the fieldset.
  * [ ] Set a placeholder on the restaurant phone number field to indicate what the data entered there should look like.
  * [ ] Each individual review on the restaurant page should be wrapped in a tag that reflects the fact that a review is a self-contained fragment that could be reused in another context. 
  * [ ] Add a footer that will appear on each page of the site, with the site name and copyright information.
  * [ ] Change the list on the restaurants page into a table, with headers for restaurant name, address, and number of reviews. Represent each restaurant in its own row in the table.

**Comment by jspencerhopkins** [comment]
[Restaurant Review Wikis](https://github.com/jspencerhopkins/restaurant_review/wiki)
