### ISSUE TITLE
18 -- HTML Tag, You're It - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#147]
#### Tasks
- [x] A WIP Issue in the class repo titled "18 -- HTML Tag, You're It " (m)
    - [x] Estimates for the top-level checkboxes (xs)
- [ ] Update your TIY-Assignments repo wiki: (s)
    - [ ] Add your thoughts on today's assignment to the existing reflections page
    - [ ] Edit the lightbulbs and struggles pages
- [ ] A branch named 18 -- HTML Tag, You're It (M)
- [ ] Tasks (XXXL)
    - [ ] Read: https://developer.mozilla.org/en-US/docs/Web/HTML/Forms_\in_HTML
    - [ ] Read:  https://developer.mozilla.org/en-US/docs/Web/HTML/Forms
    - [ ] Read: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
    - [ ] Read: https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
    - [ ] Wrap all the tags inside each form in a `fieldset` tag, and add a `legend` to the fieldset.
    - [ ] Set a placeholder on the restaurant phone number field to indicate what the data entered there should look like.
    - [ ] Each individual review on the restaurant page should be wrapped in a tag that reflects the fact that a review is a self-contained fragment that could be reused in another context
    - [ ] The data in each review - comment: "YUMM", rating: 4, etc - is a set of key-value pairs. There are tags for that format.
    - [ ] Add a footer that will appear on each page of the site, with the site name and copyright information.
    - [ ] Change the list on the restaurants page into a table, with headers for restaurant name, address, and number of reviews. Represent each restaurant in its own row in the table. 
    - [ ] In your PR, link to the new repository instead of your TIY-Assignments one.
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored MarkdownDescriptionDescription

**Comment by QueVee** [comment]
https://github.com/QueVee/MoreRails/wiki
