### ISSUE TITLE
18--HTML Tag, You're It--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#148]
#### Tasks
* [x] {S} Create a new Issue with these tasks!
* [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your restaurant_review repo.
    * [x] Create the files and directories as described in _Deliverables_.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {M} Read all items below.
    * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Forms_\in_HTML
    * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Forms
    * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Element
    * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
* [ ] Add some style to the site.
    * [ ] Wrap all the tags inside each form in a `fieldset` tag, and add a `legend` to the fieldset.
    * [x] Set a placeholder on the restaurant phone number field.
    * [ ] Add a footer that will appear on each page of the site, with the site name and copyright information.
    * [ ] Change the list on the restaurants page into a table, with headers for restaurant name, address, and number of reviews.
* [ ] {S} End of day wiki edit 
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.
