### ISSUE TITLE
18 -- HTML Tag, You're It -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#149]
# Task

* [ ] Use some of the HTML5 tags to tidy up the views in the app
   * [ ] Wrap all the tags inside each form in a fieldset tag, and add a legend to the fieldset
   * [ ] Set a placeholder on the restaurant phone number field to indicate what the data entered there should look like
   * [ ] Each individual review on the restaurant page should be wrapped in a tag that reflects the fact that a review is a self-contained fragment that could be reused in another context
   * [ ] Add a footer that will appear on each page of the site, with the site name and copyright information
   * [ ] Change the list on the restaurants page into a table, with headers for restaurant name, address, and number of reviews
   * [ ] Represent each restaurant in its own row in the table
* [ ] Update your wiki afterwards
