### ISSUE TITLE
18 -- HTML Tag, You're It -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#152]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `Rails_projects` wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `Rails_projects` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `Rails_projects` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Read the following: ***(M)***
  * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Forms_in_HTML
  * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Forms
  * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Element
  * [ ] https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements
* [ ] Each individual review on the restaurant page should be wrapped in a tag that reflects the fact that a review is a self-contained fragment that could be reused in another context. The data in each review - comment: "YUMM", rating: 4, etc - is a set of key-value pairs. There are tags for that format. ***(M)***
* [ ] Change the list on the restaurants page into a table, with headers for restaurant name, address, and number of reviews.  ***(M)***
* [ ] Add a Footer with Site Name and Copyright info ***(S)***
