### ISSUE TITLE
19 -- MVC! MVC! -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#154]
#### Tasks
* [x] {S} Create a new Issue with these tasks!
* [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your Todo list repo.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {XXL} Create a Todo list app. 
  * [ ] {XL} Level-1: Complete the functionality described below.
      * [x]  _New todo_ - Add a button to create the todo, appends it to the todo list and clears the input.
      * [ ] _Mark all as complete_ - Also requires a button for this and the 'clear completed' check box
      * [x] _Item_ - Again, a button alongside the checkbox to mark as complete. You'll also need a link to edit an item.
      * [x] _Editing_ - takes place on its own page; requires a button to save; there's no `editing` class; have a link to return to the list
      * [ ] _Persistence_ - SQLite
      * [ ] _Routing_ in Rails
  * [ ] {XL} Level-2: Add due dates to the tasks. Display tasks differently depending on whether they are overdue, due today, or due in the future (Part 2).
  * [ ] {XL} Level-3: Add support for multiple users. Each user should be able to view and edit only his/her own task list (Part 3).
  * [ ] {XL} Level-4: Add support for multiple task lists for each user. Each list should get its own label, and the user should be able to navigate between all of his/her own lists.
* [ ] {S} End of day wiki edit 
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.
