### ISSUE TITLE
19 -- MVC! MVC! -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#156]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
* [ ] Create a `TodoMVC` repo ***(S)***
* [ ] A Pull Request as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] A function To do list App ***(XL)***
  *  Level 1: Complete the functionality described above.
  *  Level 2: Add due dates to the tasks. Display tasks differently depending on whether they are overdue, due today, or due in the future.
  *  Level 3: Add support for multiple users. Each user should be able to view and edit only his/her own task list.
  *  Level 4: Add support for multiple task lists for each user. Each list should get its own label, and the user should be able to navigate between all of his/her own lists.
