### ISSUE TITLE
19--MVC!MVC!

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#157]
#### Tasks
- [x] A WIP Issue in the class repo titled "19--MVC!MVC! " (m)
    - [x] Estimates for the top-level checkboxes (xs)
- [ ] Update your repo wiki: (s)
    - [ ] Add your thoughts on today's assignment to the existing reflections page
    - [ ] Edit the lightbulbs and struggles pages
- [ ] A branch named 19--MVC!MVC!
     - [ ] Functionality should follow the [spec], with the following exceptions:
        - [ ] _New todo_ - Add a button (don't just press Enter) to create the todo, appends it to the todo list and clears the input. 
        - [ ] Mark all as complete_ - Also requires a button for this and the 'clear completed' check box
        - [ ] Item_ - Again, a button alongside the checkbox to mark as complete. You'll also need a link to edit an item. 
        - [ ] Editing_ - takes place on its own page; requires a button to save; there's no `editing` class; have a link to return to the list
        - [ ] Persistence_ - SQLite
        - [ ] Routing_ in Rails
     - [ ] Level 1: Complete the functionality described above.
      -[ ] Level 2: Add due dates to the tasks. Display tasks differently depending on whether they are overdue, due today, or due in the future. 
     - [ ] Level 3: Add support for multiple users. Each user should be able to view and edit only his/her own task list.
     - [ ] Level 4: Add support for multiple task lists for each user. Each list should get its own label, and the user should be able to navigate between all of his/her own lists.
     - [ ] In your PR, link to the new repository instead of your TIY-Assignments one.
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored MarkdownDescriptionDescription
