### ISSUE TITLE
20 -- Javascript, or maybe Yavascript -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#164]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update wiki  ***(S)*** 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
* [ ] A Pull Request in your `Rails_projects` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Make a new Rails app called `programming_languages` in a new repository to compare the languages: ***(L)***
  * [ ] Two resources: similarities and differences
    * [ ] Each similarity (or difference) should have two attributes: title and text. 
    * [ ] Each resource should have a page listing the titles of every item in the category, and the title should link to a page that has the title and text.
    * [ ] The list page should also have a link to create a new similarity (or difference). 
    * [ ] The detail page for each similarity (or difference) should have: a link to edit and a button to delete it. 
* [ ] Read over the Document Object Model, and type out pages for the first three examples of using Javascript on a web page. Add to public/ folder of the new app. ***(M)***
* [ ] Read overview of the language  ***(S)***
