### ISSUE TITLE
20--Javascript, or maybe Yavascript--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#165]
#### Tasks
* [x] {S} Create a new Issue with these tasks!
* [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P repository called `programming_languages`.
    * [x] Create the files and directories as described in _Deliverables_.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {M} Read all required documentation.
    * [x] [overview of the language](https://developer.mozilla.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript)
    * [ ] [Document Object Model](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction)
* [ ] {XL} Create a rails app to demonstrate the differences and similarities of Ruby and Javascript. 
    * [x] Create two resources, similarities and differences.
    * [x] Create two attributes: title and text for each similarity (or difference). 
    * [x] Create a page listing the titles of every item in the category for each resource.
    * [x] Create a link where the title links to a page that has the title and text.
    * [x] Create a link for the list page to create a new similarity (or difference).
    * [x] A detail page for each similarity (or difference) should have a link to edit and a button to delete it.
    * [ ] Type out pages for the first three examples from [examples of using Javascript on a web page](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Examples).
* [ ] {S} End of day wiki edit 
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.
