### ISSUE TITLE
20 -- Javascript, or maybe Yavascript - J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#166]
#### **Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `programming_languages` wiki  ***(S)***
   * [ ] Assignment Evaluation
   * [ ] Lightbulbs
   * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `programming_languages` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `programming_languages` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] SOME TASK ***(T-SHIRT SIZE)***
* [ ] SOME TASK 2 ***(T-SHIRT SIZE)***
* [ ] SOME TASK 3 ***(T-SHIRT SIZE)***

**Comment by jspencerhopkins** [comment]
[Programming Language Wikis](https://github.com/jspencerhopkins/programming_languages/wiki)
