### ISSUE TITLE
21 -- AJAX, or maybe AYAX - J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#169]
#### **Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `restaurant_review` wiki  ***(S)***
* [ ] Create a branch in your `restaurant_review` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `restaurant_review` repo ***(S)***
* [ ] Comments on your WIP Issue ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] SOME TASK ***(T-SHIRT SIZE)***
* [ ] SOME TASK 2 ***(T-SHIRT SIZE)***
* [ ] SOME TASK 3 ***(T-SHIRT SIZE)***

**Comment by jspencerhopkins** [comment]
[Restaurant Review Wiki](https://github.com/jspencerhopkins/restaurant_review/wiki)
