### ISSUE TITLE
21 -- AJAX, or maybe AYAX - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#170]
# 21 -- AJAX, or maybe AYAX

#### Tasks
 
- [x] A WIP Issue in the class repo  21 -- AJAX, or maybe AYAX(m)
    - [x] Estimates for the top-level checkboxes (xs) 
- [ ] Tasks and deliverables in the restaurant review app: (XXXL)
    - [ ] Hide the form for adding a new review, 
    - [ ] and make it appear in response to clicking on a link that says "Add a review".
    - [ ] When a new review is added, have it appear at top of the review list rather than generating a whole new page.
    - [ ] Reviews should include a link to edit them, but only when they are viewed by the user who created them. 
       - [ ] Place the edit link for a review in the same `<p>` tag as the "Posted by" information. 
    - [ ] Reviews should include a link to delete them, but only when they are viewed by the user who created them. 
       - [ ] Place the delete button for a review in the same `<p>` tag as the "Posted by" information. If a review is deleted, remove it from the list without generating a whole new page. 
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored MarkdownDescriptionDescription
