### ISSUE TITLE
21--AJAX, or maybe AYAX--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#171]
#### Tasks
* [x] {S} Create a new Issue with these tasks!
* [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your `restaurant_review` repo.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {L} Level 1
    * [x] Hide the form for adding a new review, and make it appear in response to clicking on a link that says "Add a review".
    * [x] When a new review is added, have it appear at top of the review list rather than generating a whole new page.
    * [ ] Reviews should include links to edit or delete them, but only when they are viewed by the user who created them. Place the edit link and delete button for a review in the same `<p>` tag as the "Posted by" information. If a review is deleted, remove it from the list without generating a whole new page.
* [ ] {XL} Expert level
    * [ ] Have the edit link and delete button present in a user's reviews but be invisible unless the user is hovering over the containing `<p>` tag.
    * [ ] Remove the delete button for reviews posted more than an hour ago.
* [ ] {XXL}Nightmare level
    * [ ] Have the form for editing a review appear right underneath the review. When the form is submitted, replace the old version of the review with the new one, and add a visible signal that a change occurred.
    * [ ] Include a link to let a user cancel the edit before submitting it.
* [ ] {S} End of day wiki edit 
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.
