### ISSUE TITLE
21--AJAX, or maybe AYAX -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#172]
# Task

### Return to the restaurant review app and make the following changes:

* [ ] Hide the form for adding a new review, and make it appear in response to clicking on a link that says "Add a review"
* [ ] When a new review is added, have it appear at top of the review list rather than generating a whole new page
* [ ] Reviews should include links to edit or delete them, but only when they are viewed by the user who created them. Place the edit link and delete button for a review in the same `<p>` tag as the "Posted by" information. If a review is deleted, remove it from the list without generating a whole new page

### Expert level

* [ ] Have the edit link and delete button present in a user's reviews but be invisible unless the user is hovering over the containing `<p>` tag.
* [ ] Remove the delete button for reviews posted more than an hour ago.

### Nightmare mode

* [ ] Have the form for editing a review appear right underneath the review. When the form is submitted, replace the old version of the review with the new one, and add a visible signal that a change occurred.
* [ ] Include a link to let a user cancel the edit before submitting it.

* [ ] Update your wiki afterwards
