### ISSUE TITLE
22 -- Two Do MVC -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#177]
# Task

* [ ] build the [TodoMVC project](http://todomvc.com/) in Rails. To see the app in action, click on any of the links under the "Examples" tab
* [ ] The functionality should follow the [spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md#functionality), with the following exceptions:
   * _Persistence_ - SQLite
   * _Routing_ in Rails
* [ ] You can make use of the HTML in their [template](https://github.com/tastejs/todomvc-app-template/blob/master/index.html) and the CSS in the [template for that](https://github.com/tastejs/todomvc-app-css/blob/master/index.css). Use Rails helper methods wherever possible (in the form, for example).
### This project will have multiple levels of difficulty
* [ ] Level 1: Complete the functionality described above.
* [ ] Level 2: Add due dates to the tasks. Display tasks differently depending on whether they are overdue, due today, or due in the future. 
* [ ] Level 3: Add support for multiple users. Each user should be able to view and edit only his/her own task list.
* [ ] Level 4: Add support for multiple task lists for each user. Each list should get its own label, and the user should be able to navigate between all of his/her own lists.
* [ ] Once completed, place this functional todo list application, in its own repository
