### ISSUE TITLE
22--Two Do MVC--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#178]
#### Tasks
* [x] {S} Create a new Issue with these tasks!
* [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} Use the Terminal in your computer to:
    * [x] Create a new repo named `Two Do MVC`.
    * [x] create a W.I.P branch of your `Two Do MVC` repo.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {L} Level 1-Complete the functionality.
    * [x] When there are no todos, `#main` and `#footer` should be hidden.
    * [x] New todos are entered in the input at the top of the app and will display once you hit enter.
    * [ ] Todos can be marked as completed.
    * [ ] Todos can be edited/updated.
    * [ ] Todos can be deleted. 
* [ ] {L} Level 2
    * [ ] Add due dates to the tasks.
    * [ ] Display tasks differently depending on whether they are overdue, due today, or due in the future.
* [ ] {M} Level 3
    * [x] Add support for multiple users.
    * [x] Each user should be able to view and edit only his/her own task list.
* [ ] {L} Level 4
    * [ ] Add support for multiple task lists for each user.
    * [x] Each list should get its own label.
    * [ ] user should be able to navigate between all of his/her own lists.
* [x] {S} End of day wiki edit 
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ]  {S} 2 thumbs up.

**Comment by Peterortiz82** [comment]
[Wiki Page](https://github.com/Peterortiz82/TIY-Assignments/wiki)
