### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by malkin28025** [TheIronYard--Orlando/ROR--2015--SPRING#179]
#### Tasks

* [ ] Create a new Issue WIP issue in the class repo named appropriately(S)
* [ ] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_(S)
* [ ] Night update your wiki: Assignment Evaluation, _Light Bulbs_, and _Things I Don't Get Yet_(M)
* [ ]  TodoMVC project(XL) 
	* [ ] New todo - Add a button (don't just press Enter) to create the todo, appends it to the todo list and clears the input.
	* [ ] Mark all as complete - Also requires a button for this and the 'clear completed' check box
	* [ ] Item - Again, a button alongside the checkbox to mark as complete. You'll also need a link to edit an item.
	* [ ] Editing - takes place on its own page; requires a button to save; there's no editing class; have a link to return to the list
	* [ ] Persistence - SQLite
	* [ ] Routing in Rails
* [ ] Create a branch in your `TIY-Assignments` repo(S) 
	* [ ] A Pull Request in your TIY-Assignments
