### ISSUE TITLE
22 -- Two Do MVC - Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#180]
#### Tasks

- [x] A WIP Issue in the class repo  (m)
- [x] Estimates for the top-level checkboxes (xs) 
- [ ] Tasks and deliverables in the Todo app: (XXXL)
    - [ ] build the [TodoMVC project](http://todomvc.com/) in Rails 
    - [ ] functionality should follow the [spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md#functionality), with the following exceptions:
         * _Persistence_ - SQLite
         * _Routing_ in Rails
    - [ ] Remove some lines from the HTML template. 
       - [ ]  <script src= and <link rel="stylesheet" href="node_modules/
    - [ ]  Level 1: Complete the functionality described above.
    - [ ] Level 2: Add due dates to the tasks.
    - [ ]  Level 3: Add support for multiple users. 
    - [ ]  Level 4: Add support for multiple task lists for each user. 
- [ ] a series of commits after each milestone or hour. (S)
- [ ] A Pull Request (PR) (m)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored MarkdownDescriptionDescription

**Comment by QueVee** [comment]
[Wiki page] (https://github.com/QueVee/two-do-MVC/wiki)
