### ISSUE TITLE
22 -- Two Do MVC- J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#182]
#### **Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)***
  * [ ] Assignment Evaluation
  * [ ] Lightbulbs
  * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `mvc_js` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `mvc_js` ***(S)***
* [ ] Comments on your WIP Issue ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Build the [TodoMVC project](http://todomvc.com/) in Rails ***(XL)***
  * [ ] functionality should follow the [spec](https://github.com/tastejs/todomvc/blob/master/app-spec.md#functionality), with the following exceptions:
    * _Persistence_ - SQLite
    * _Routing_ in Rails
  * [ ] You can make use of the HTML in their [template](https://github.com/tastejs/todomvc-app-template/blob/master/index.html) and the CSS in the [template for that](https://github.com/tastejs/todomvc-app-css/blob/master/index.css)
  * [ ] Remove some lines from the HTML template. Towards the bottom are two lines that start:
    * [ ] <script src=
    * [ ] <link rel="stylesheet" href="node_modules/
* [ ] Level 2: ***(L)***
  * [ ] Add due dates to the tasks. Display tasks differently depending on whether they are overdue, due today, or due in the future. 
* [ ] Level 3: ***(XXL)***
  * [ ] Add support for multiple users. Each user should be able to view and edit only his/her own task list.
* [ ] Level 4: ***(XXXL)***
  * [ ] dd support for multiple task lists for each user. Each list should get its own label, and the user should be able to navigate between all of his/her own lists.

**Comment by jspencerhopkins** [comment]
[mvc_js wiki](https://github.com/jspencerhopkins/mvc_js/wiki)
