### ISSUE TITLE
23 -- All-The-Things - Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#184]
#### Tasks
- [x] {S} Create a new Issue with these tasks!
- [x] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
- [x] {S} Use the Terminal in your computer to:
  - [x] create a repo.
  - [x] Add and commit your work.
  - [x] Push your commits to Github.
  - [ ] In Github, open a PR.
- [x] Errors app
  - [x] Setup routes, controllers, models, ect.
  - [x] create users
  - [x] allow users to make post with images
  - [x] set authentication so that users can only edit and delete their own post
  - [x] add view count.
  - [ ] create a comment section for users to leave comments on post. 
  - [ ] allow vote up on comments
  - [ ] set up categories
- [ ] {S} End of day wiki edit 
  - [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
  - [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
- [ ]  {S} 2 thumbs up.

**Comment by Peterortiz82** [comment]
[New Repo-Rails_error_tracker](https://github.com/Peterortiz82/rails_error_tracker)
