### ISSUE TITLE
Final Project- how long- Joe Cursi

### ISSUE THREAD

**Issue by malkin28025** [TheIronYard--Orlando/ROR--2015--SPRING#193]
#### Tasks
- [X] Come up with Idea for functionality
- [X] Write out User Stories and make mock-up of pages
- [X] Come up with all the technologies necessary to accomplish project
- [ ]  Ensure that following functionality is completed:
  - [ ] Can view home page with working links to rest of site.
  - [ ] Add/Update/Comments box to be approved by Admin.
  - [ ] Victim Memorial
          \* [X] Inspiration for site
          \* [ ] Create API with list of all victims stories
          \* [ ] Link to incidents: name, state, year
          \* [ ] Search Box- can search data base by name, state, year
  - [ ] Links to Survivor Resources
          \* [ ] Link web sites
          \* [ ] Link to literature
          \* [ ] Link to crime victims rights
  - [ ] News- 
    - [ ] Create api for news updates concerning Gun Control/ Gun Homicides to be approved by Admin.

**Comment by malkin28025** [comment]
[WIP] https://github.com/malkin28025/How-long-/pull/1
