### ISSUE TITLE
02 -- High Functioning -- J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#20]
#### Tasks
* [ ] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [ ] Work through some introductory lessons at [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) (1-3 of the Introductory Sequence on the Main menu, and 1-4 of Push & Pull on the Remote menu). There's a lot of animated branching diagrams in that tutorial, so you'll have to concentrate on using them to help you learn instead of just looking at them. Like we do during lecture, try to imagine what will happen next for each step.
* [ ] End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [ ] End of day wiki edit **(please do these as your final tasks)**
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ] Use the Terminal in your computer to:
    * [ ] create a branch of *your* `TIY-Assignments` repo called `feature/02--high-functioning`
    * [ ] switch to the new branch
    * [ ] Create at least one file and directory as described above in _Deliverables_.
    * [ ] Add and commit your work every hour or at every breakthrough (whichever comes first)
    * [ ] Push your commits to Github
    * [ ] In Github, open a PR _from_ `feature/02--high-functioning` _into_ `master`

**Comment by jspencerhopkins** [comment]
https://github.com/jspencerhopkins/TIY-Assignments/wiki
