### ISSUE TITLE
02 -- High Functioning -- Jeff Winkler

### ISSUE THREAD

**Issue by palmbeachjeff** [TheIronYard--Orlando/ROR--2015--SPRING#23]
#### Tasks
* [x] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [x] Work through some introductory lessons at [Learn Git Branching](http://pcottle.github.io/learnGitBranching/) (1-3 of the Introductory Sequence on the Main menu, and 1-4 of Push & Pull on the Remote menu). There's a lot of animated branching diagrams in that tutorial, so you'll have to concentrate on using them to help you learn instead of just looking at them. Like we do during lecture, try to imagine what will happen next for each step.
* [x] End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [x] End of day wiki edit **(please do these as your final tasks)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [x] Use the Terminal in your computer to:
    * [x] create a branch of *your* `TIY-Assignments` repo called `feature/02--high-functioning`
    * [x] switch to the new branch
    * [x] Create at least one file and directory as described above in _Deliverables_.
    * [x] Add and commit your work every hour or at every breakthrough (whichever comes first)
    * [x] Push your commits to Github
    * [x] In Github, open a PR _from_ `feature/02--high-functioning` _into_ `master`

**Comment by palmbeachjeff** [comment]
M - Work through Learn Git
S - Wiki Edit
S - Wiki Edit (Final)
XL - Use Terminal

**Comment by bgates** [comment]
Jeff, if you don't feel comfortable with the code we developed Wednesday to complete this assignment, you need to let me know.
Also, please move the wiki pages you wrote - Assignment Eval, Lightbulbs, and Struggles - into the wiki for your repo. GitHub gives you a link labeled 'wiki' in the sidebar of the front page of every repo you create.

**Comment by bgates** [comment]
Closed checkboxes are always good, but one checkbox talks about a pull request, and if you have one of those linked to this issue there should be a link to the pull request on this page....
