### ISSUE TITLE
03 -- Method to the Madness -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#26]
#### Tasks
* [x] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [x] End of lab wiki edit **{S}
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [x] Use the Terminal in your computer to:{XL}
    * [x] create a branch of *your* `TIY-Assignments` repo 
    * [x] switch to the new branch
    * [x] Create at least one file and directory as described above in _Deliverables_.
    * [x] Add and commit your work every hour or at every breakthrough (whichever comes first)
    * [x] Push your commits to Github
    * [x] In Github, open a PR

**Comment by Peterortiz82** [comment]
PR
https://github.com/Peterortiz82/TIY-Assignments/pull/5

Wiki Pages
https://github.com/Peterortiz82/TIY-Assignments/wiki
