### ISSUE TITLE
03 -- Method to the Madness -- J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#27]
#### Tasks
* [x] {S} A _WIP Issue_ in the class repo
    * [x] Titled appropriately
    * [x] With checkboxes for the tasks and any subtask you can identity
    * [x] Estimate for top-level checkboxes
* [x] {S} Update your `TIY-Assignments` wiki
* [x] {S} Create a branch in your `TIY-Assignments` repo, named appropriately
    * [x] include a `code/` folder with files for each of the three (or four) coding challenges you undertake
* [x] {L} The THREE programming challenges
    * [x] Extent your Fixnum#to_roman method to work up to 2015
    * [x] Write a method on the `Fixnum` class which returns the the factorial of a number
    * [x] Write a method on the `Fixnum` class to convert a number to its name in English
* [x] {XS} A Pull request in your `TIY-Assignments` folder as on previous assignments
* [x] {XS} Comments on your WIP Issue as on previous assignments

**Comment by jspencerhopkins** [comment]
https://github.com/jspencerhopkins/TIY-Assignments/wiki

**Comment by jspencerhopkins** [comment]
[PR] (https://github.com/jspencerhopkins/TIY-Assignments/pull/12)

**Comment by jspencerhopkins** [comment]
Not thrilled with my number_to_english solution, but it works.
I used Pine book to help guide me through it, but the solution isn't as concise (nor straightforward) as it could and should be.  Hope to spend some more time on it before class starts this morning.
