### ISSUE TITLE
03 -- Method to the Madness -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#29]
#### Tasks

* [x] A _WIP Issue_ in the class repo **S
  * [x] Titled appropriately
  * [x] With check boxes for the tasks *and any subtasks you can identify*
  * [x] Estimates for the top-level checkboxes
* [x]  Update your `TIY-Assignments` wiki **S
* [x] Create a branch in your `TIY-Assignments` repo, named appropriately -- **S (Coding Challenges)
  * [x]  include a `code/` folder with files for each of the three (or four) coding challenges you undertake       
      * [x] Extend your Fixnum#to_roman method to work up to 2015.
      * [x] A factorial of an integer is the product of all positive integers up to and including that integer. For       example 6 factorial = 6 * 5 * 4 * 3 * 2 * 1. Write a method on the `Fixnum` class which returns the factorial   of a number.
     *  [x] Write a method on the `Fixnum` class to convert a number to its name in English.
     *  EXPERT LEVEL: Write a function that can do addition or multiplication in English. For example    given "twenty three times seventy eight", it should return "one thousand seven hundred ninety
 four".
     * SUPER EXPERT LEVEL: Write a function that can do any basic arithmetic operation - addition,    subtraction, multiplication, or division - in English, accepting a string as input and returning one
   as output.
* [x] A Pull Request in your `TIY-Assignments` folder as on previous assignments **S
* [x] Comments on your WIP Issue as on previous assignments **S

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki

**Comment by angelabier1** [comment]
[Pull Request](https://github.com/angelabier1/TIY-Assignments/pull/4)

**Comment by Peterortiz82** [comment]
:+1:

**Comment by angelabier1** [comment]
THANK YOU @Peterortiz82 !!

**Comment by AJean144** [comment]
:+1:

**Comment by bgates** [comment]
I don't know what happened in that num_to_words.rb file. If you try to run it you'll see our friend the error message. That means it shouldn't have been committed. At least one problem with it is that it's missing an end statement, which is the kind of thing that should be noticed by any other developer who looks at the code. That means any other developer who looks at the code (looking at you guys, @Peterortiz82  and @AJean144) should notice the problem and leave *that* as a comment - "I think you're missing a couple `end` statements" - rather than just giving a thumbs up and going on your way.
