### ISSUE TITLE
03 -- Method to the Madness -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#30]
# 03 -- Method to the Madness

## Description

Three programming challenges for today:

* Extend your Fixnum#to_roman method to work up to 2015.

* A factorial of an integer is the product of all positive integers up to and including that integer. For example 6 factorial = 6 * 5 * 4 * 3 * 2 * 1. Write a method on the `Fixnum` class which returns the factorial of a number.

* Write a method on the `Fixnum` class to convert a number to its name in English.

* EXPERT LEVEL: Write a function that can do addition or multiplication in English. For example given "twenty three times seventy eight", it should return "one thousand seven hundred ninety four".

* SUPER EXPERT LEVEL: Write a function that can do any basic arithmetic operation - addition, subtraction, multiplication, or division - in English, accepting a string as input and returning one as output.

### Learning Objectives

After completing this assignment, you should begin to understand how to:
* formulate expectations for your code step-by-step 
* write the simplest code that meets your expectations
* write the simplest expectation that breaks
* use the Ruby concept of `self`
* extend the capabilities of a built-in class by writing new methods

### Deliverables

* A _WIP Issue_ in the class repo
  * Titled appropriately
  * With check boxes for the tasks *and any subtasks you can identify*
  * Estimates for the top-level checkboxes
* Update your `TIY-Assignments` wiki
* Create a branch in your `TIY-Assignments` repo, named appropriately
  * include a `code/` folder with files for each of the three (or four) coding challenges you undertake
* A Pull Request in your `TIY-Assignments` folder as on previous assignments
* Comments on your WIP Issue as on previous assignments

#### Tasks

* [x] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [x] End of lab wiki edit
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [x] Use the Terminal in your computer to:
    * [x] create a branch of *your* `TIY-Assignments` repo called `feature/03--method-to-the-madness`
    * [x] switch to the new branch
    * [x] Create at least one file and directory as described above in _Deliverables_.
    * [x] Add and commit your work every hour or at every breakthrough (whichever comes first)
    * [x] Push your commits to Github
    * [x] In Github, open a PR _from_ `feature/03--method-to-the-madness` _into_ `master`
* [x] End of day wiki edit **(please do these as your final tasks)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.

**Comment by bgates** [comment]
PR, please?
