### ISSUE TITLE
04 -- Blackjack -- J. Spencer Hopkins

### ISSUE THREAD

**Issue by jspencerhopkins** [TheIronYard--Orlando/ROR--2015--SPRING#36]
#### Tasks
* [x] {S} A _WIP Issue_ in the class repo
    * [x] Titled appropriately
    * [x] With checkboxes for the tasks and any subtask you can identity
    * [x] Estimate for top-level checkboxes
* [x] {S} Update your `TIY-Assignments` wiki
* [x] {S} Create a branch in your `TIY-Assignments` repo, named appropriately
    * [x] include a `docs/` folder with file for the blackjack instructions
* [x] {XS} A Pull request in your `TIY-Assignments` folder as on previous assignments
* [x] {XS} Comments on your WIP Issue as on previous assignments
* [x] {M} Explain the game of Blackjack in words
    * [x] Focus on the nouns and verbs
* [ ] {XXXL} Create Blackjack & Blackjack test in Ruby

**Comment by jspencerhopkins** [comment]
**Wikis**
https://github.com/jspencerhopkins/TIY-Assignments/wiki

**Comment by jspencerhopkins** [comment]
Lumped Blackjack in Words & Blackjack assignments together

**Comment by bgates** [comment]
Actually, "Needs More English", but I don't have a label for that.
