### ISSUE TITLE
05 -- Blackjack in Words -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#38]
# Tasks

* [x] {S} Update the `TIY-Assignments` wiki with thoughts about the lecture and assignments
* [x] {S} Create a branch in `TIY-Assignments` and in the `docs/` folder, make a file for the blackjack instructions

#### The Mission

* [x] {M} Learn about the card game "Black-Jack" and write down every possible noun and verb in the game
* [x] {S} A Pull request must be done within the `TIY-Assignments` folder just like every other day

###### Wrapping up

* [x] {S} Once everything is completed add final comments on your WIP Issue as always

**Comment by AJean144** [comment]
https://github.com/AJean144/TIY-Assignments/pull/4

**Comment by bgates** [comment]
That's a decent writeup of blackjack.
