### ISSUE TITLE
04 -- Blackjack in words -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#41]
#### Tasks
* [X] {S} A WIP Issue in the class repo
* [X] {S} Estimate all the top-level tasks 
* [x] {S} Update your TIY-Assignments wiki
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [x] {L} Use the Terminal in your computer to:
    * [X] create a branch of *your* `TIY-Assignments` repo named appropriate 
    * [X] Create at least one file and directory 
    * [X] Add and commit your work every hour or at every breakthrough (whichever comes first)
    * [X] Push your commits to Github
     *[ ] A Pull request in your TIY-Assignments folder as on previous assignments
* [X] {S} Explain the game of Blackjack in words

**Comment by Peterortiz82** [comment]
[My Wiki Page](https://github.com/Peterortiz82/TIY-Assignments/wiki)

**Comment by Peterortiz82** [comment]
[Pull Request](https://github.com/Peterortiz82/TIY-Assignments/pull/7)

**Comment by bgates** [comment]
The words are there, now we need to get the Ruby to go with them (not part of this assignment), and we'll be set.
