### ISSUE TITLE
04 -- Blackjack in words -- Joe Cursi

### ISSUE THREAD

**Issue by malkin28025** [TheIronYard--Orlando/ROR--2015--SPRING#42]
#### Tasks

* [X] Create a new Issue WIP isuue in the class repo named appropriately(S)
* [X] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_(S)
* [X] Edit your wiki: Assigment Evaluation, _Light Bulbs_, and _Things I Don't Get Yet_(M)
* [X] Create a new page in your `TIY-Assignments` repo(M)
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately 
	* [X] A Pull Request in your TIY-Assignments folder

**Comment by malkin28025** [comment]
https://github.com/malkin28025/TIY-Assignments/blob/master/04%20--%20Blackjack%20in%20words%20--%20Joe%20Cursi

**Comment by bgates** [comment]
No PR, no time to look at this again
