### ISSUE TITLE
04 -- Blackjack -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#44]
#### Tasks

* [x] A _WIP Issue_ in the class repo **S
  * [x] Titled appropriately
  * [x] With check boxes for the tasks *and any subtasks you can identify*
  * [x] Estimates for the top-level checkboxes
* [x]  Update your `TIY-Assignments` wiki **S
* [x] Create a branch in your `TIY-Assignments` repo, named appropriately -- **S
* [x] A Pull Request in your `TIY-Assignments` folder as on previous assignments **S
* [x] Comments on your WIP Issue as on previous assignments **S
* [x] Explain the game of Blackjack in English **M
* [x] Translate English into Code **XL
* [x] Run tests on Code **XL

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki

**Comment by angelabier1** [comment]
[Pull Requests](https://github.com/angelabier1/TIY-Assignments/pull/8)
