### ISSUE TITLE
05 -- This Is Only A Test -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#45]
#### Tasks
* [ ] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [ ] Sort these tasks into the order in which you'll begin them
* [ ] Download the [Ruby Koans](http://rubykoans.com) into your repo and work through them up to the end of the about_symbols.rb. 
* [ ] End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [ ] End of day wiki edit **(please do these as your final tasks)**
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ] Use the Terminal in your computer to:
    * [ ] create a branch of *your* `TIY-Assignments` repo called `feature/05--this-is-only-a-test`
    * [ ] switch to the new branch
    * [ ] Create at least one file and directory as described above in _Deliverables_.
    * [ ] Add and commit your work every hour or at every breakthrough (whichever comes first)
    * [ ] Push your commits to Github
    * [ ] In Github, open a PR _from_ `feature/05--this-is-only-a-test` _into_ `master`

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki
