### ISSUE TITLE
05 -- This Is Only A Test -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#47]
#### Tasks
* [X] {S} Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
* [X] {S} Sort these tasks into the order in which you'll begin them
* [x] {S} End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [X] {XL} Use the Terminal in your computer to:
    * [x] create a branch of *your* `TIY-Assignments` repo called `feature/05--this-is-only-a-test`
    * [x] switch to the new branch
    * [x] Create at least one file and directory as described above in _Deliverables_.
    * [x] Add and commit your work every hour or at every breakthrough (whichever comes first)
    * [x] Push your commits to Github
    * [x] In Github, open a PR _from_ `feature/05--this-is-only-a-test` _into_ `master`  
    * [x] Start on deck for Blackjack
* [x] {M} Download the [Ruby Koans](http://rubykoans.com) into your repo and work through them up to the end of the about_symbols.rb. 
* [x] {S} End of day wiki edit **(please do these as your final tasks)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.

**Comment by Peterortiz82** [comment]
[My Wiki Page](https://github.com/Peterortiz82/TIY-Assignments/wiki)
