### ISSUE TITLE
05 -- This is only a Test -- Jeff Winkler

### ISSUE THREAD

**Issue by palmbeachjeff** [TheIronYard--Orlando/ROR--2015--SPRING#49]
#### Tasks
- [x] Sort these tasks into the order in which you'll begin them
- [x] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_
- [x] End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)** (S)
  - [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
  - [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
- [ ] Download the [Ruby Koans](http://rubykoans.com) into your repo and work through them up to the end of the about_symbols.rb. (L)
- [x] Use the Terminal in your computer to: (XL)
  - [x] create a branch of _your_ `TIY-Assignments` repo called `feature/05--this-is-only-a-test`
  - [x] switch to the new branch
  - [x] Create at least one file and directory as described above in _Deliverables_.
  - [x] Add and commit your work every hour or at every breakthrough (whichever comes first)
  - [x] Push your commits to Github
  - [x] In Github, open a PR _from_ `feature/05--this-is-only-a-test` _into_ `master`  
- [x] End of day wiki edit **(please do these as your final tasks)** (S)
  - [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
  - [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.

**Comment by palmbeachjeff** [comment]
Card_Test redo:
https://github.com/palmbeachjeff/TIY-Assignments/pull/4

**Comment by palmbeachjeff** [comment]
Koans:

https://github.com/palmbeachjeff/TIY-Assignments/tree/05--This-is-only-a-test/koans
