### ISSUE TITLE
07 -- Methodtation -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#58]
#### Tasks

* [ ] A _WIP Issue_ in the class repo **S
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki **S
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately -- **S
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments **S
* [ ] Comments on your WIP Issue as on previous assignments **S
* [ ] Create subdirectories in ` /code` directory for: **S
  * [ ] `/wolf`
  * [ ] `/moguls`
  * [ ] `/koans`
* [ ] a `/doc` directory with examples of each method from list of frequently used methods **M
* [ ] Complete the following files and place in related subdirectories **XL
  * [ ] wolf_test.rb
  * [ ] wolfpack_test.rb
  * [ ] wolf.rb
  * [ ] wolfpack.rb
  * [ ] mogul_test.rb
  * [ ] investment_club_test.rb
  * [ ] mogul.rb
  * [ ] investment_club.rb
  * [ ] koans (finished or started)

**Comment by angelabier1** [comment]
[Pull Request](https://github.com/angelabier1/TIY-Assignments/pull/10)

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki
