### ISSUE TITLE
07--Methodtation--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#60]
#### Tasks
* [X] {S} Create a new Issue with these tasks!
* [X] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {M} End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**
    * [X] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [X] {L} Clean up your Github branches and add directories for code assignments. 
* [x] Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your `TIY-Assignments` repo called 07--Methodtation.
    * [x] switch to the branch you just created with `git checkout`
    * [x] Create the files and directories as described in _Deliverables_.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [ ] {M} End of day wiki edit **(please do these as your final tasks)**
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ] {L} Create a /doc directory with examples of each method from my list of frequently used methods
* [ ] {XXL} Complete code assignments.
     * [ ] Wolf
     * [ ] Mogul
     * [ ] Koans
* [ ] {S} Get :+1: :+1:

**Comment by Peterortiz82** [comment]
[Wiki Page](https://github.com/Peterortiz82/TIY-Assignments/wiki)
