### ISSUE TITLE
07--Methodtation--Joe Cursi

### ISSUE THREAD

**Issue by malkin28025** [TheIronYard--Orlando/ROR--2015--SPRING#61]
#### Tasks

* [X] Create a new Issue WIP issue in the class repo named appropriately(S)
* [X] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_(S)
* [ ] End of lab edit your wiki: Assignment Evaluation, _Light Bulbs_, and _Things I Don't Get Yet_(M)
* [ ] Set up cold directory called code/ with:(M)
        * [ ] /wolf
        * [ ] /moguls
        * [ ] /koans
* [ ] Set up cold folder called doc/ with:(M)
        * [ ] Examples of frequently used methods discussed in class and methods you don't understand(L)
* [ ] Create a new page in your `TIY-Assignments` repo(M)
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately(M)
	* [ ] A Pull Request in your TIY-Assignments folder(M)
* [ ] End of day edit your wiki: Assignment Evaluation, _Light Bulbs_, and _Things I Don't Get Yet_(S)
