### ISSUE TITLE
07--Methodtation -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#66]
# 07 -- Methodtation

## Description

Meditate on methods.

Run through the koans up to about_iteration.rb. Try to solve every koan in a file the first time you open it, rather than letting the koans give you the answer for each one.

Go through the rest of my frequently used methods and provide an example for each one you understand. Make a separate list containing only the ones you don't understand.

As the final part of tonight's Ruby, there is at least one objective set for each of the investment club and the wolfpack that haven't been met yet. Get those finished off, and take another look at blackjack and see what progress you can make.

Last thing, we need some GitHub cleanup. Adjust *each branch outside of master* to contain *only the files unique to that branch*. Make sure you have a pull request for each of those branches connected to the issue you opened for that branch (ie that day's assignment). 

### Learning Objectives

You're going to get a basic vocabulary of methods and what can be done with them by writing examples, revisit the basics and see some finer points in the koans, and put the built-in methods to work writing methods in your own tests and related classes.

### Performance Objectives

* Clean up GitHub! One pull request per issue, connected to a branch with unique files, each pull request with two thumbs up *if the code is ready for my inspection*.

* Knock out those koans. Only include koans into your *branch* once you've completed them. (Don't delete them from your *directory*, just have git forget about them - https://scotch.io/quick-tips/how-to-use-git-remove-without-deleting-the-files)

* Finish up the investment club and wolfpack. 

### Deliverables

* a `/code` directory with three subdirectories:
  * `/wolf`, with completed wolf_test.rb, wolfpack_test.rb, wolf.rb, and wolfpack.rb
  * `/moguls`, with completed mogul_test.rb, investment_club_test.rb, mogul.rb, and investment_club.rb
  * `/koans`, with *only those koans in which you've made progress* (finished, or at least started)
* a `/doc` directory with examples of each method from my list of frequently used methods
  * the list you're unsure about can go in a separate file in that directory

###Tasks

* [x] A _WIP Issue_ in the class repo ***(S)***
  * [x] Titled appropriately
  * [x] With check boxes for the tasks *and any subtasks you can identify*
  * [x] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)***
  * [ ] End of Lab *(Due by 5 pm)*: 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet*
  * [ ] End of Day: 
	    * [ ] Assignment Evaluation
	   * [ ] Lightbulbs
	   * [ ] Things I Don’t Get Yet*
* [x] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [x] Run through the koans up to `about_iteration.rb`
* [x] Go through the rest of my frequently used methods and provide an example for each one you understand
* [ ] Make a separate list containing only the ones you don't understand

* [ ] The investment club and the wolfpack
       * [ ] Finish up the investment club
       * [ ] Finish up the wolfpack
* [ ] Take a look at Blackjack and finish that up
* [x] GitHub cleanup
       * [x] Clean up github branches so that each day reflects the work that was done that day
* [ ] a `/code` directory with three subdirectories:
  * [ ] `/wolf`, with completed wolf_test.rb, wolfpack_test.rb, wolf.rb, and wolfpack.rb
  * [ ] `/moguls`, with completed mogul_test.rb, investment_club_test.rb, mogul.rb, and investment_club.rb
  * [ ] `/koans`, with *only those koans in which you've made progress* (finished, or at least started)
* [ ] a `/doc` directory with examples of each method from my list of frequently used methods
  * [ ] the list you're unsure about can go in a separate file in that directory

**Comment by bgates** [comment]
No PR, no time to look at this again
