### ISSUE TITLE
08--Pokerb--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#68]
#### Tasks
* [X] {S} Create a new Issue with these tasks!
* [X] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [x] {S} Use the Terminal in your computer to:
    * [x] create a W.I.P branch of your `TIY-Assignments` repo.
    * [x] switch to the branch you just created with `git checkout`
    * [x] Create the files and directories as described in _Deliverables_.
    * [x] Add and commit your work.
    * [x] Push your commits to Github.
    * [x] In Github, open a PR.
* [x] {S} End of day wiki edit **(please do these as your final tasks)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ] {XXL} Complete code assignments with 2 thumbs up.
