### ISSUE TITLE
09 -- Feeling Super, Thanks for Asking -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#76]
**Tasks**

* [ ] A _WIP Issue_ in the class repo ***(S)***
  * [ ] Titled appropriately
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the top-level checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)***
  * [ ] End of Lab *(Due by 5 pm)*: 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
  * [ ] End of Day: 
	   * [ ] Assignment Evaluation
	   * [ ] Lightbulbs
	   * [ ] Things I Don’t Get Yet
* [ ] Create a branch in your `TIY-Assignments` repo, named appropriately  ***(S)***
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] Create `/code/cards` directory ***(M)***
  * [ ] `/blackjack`, with completed blackjack_card_test.rb and blackjack_card.rb
  * [ ] `/three_card_poker` with completed poker_card_test.rb and poker_card.rb 
  * [ ] completed card.rb and card_test.rb in `/code/cards`
* [ ] `/code/koans` with only koans in which progress has been made ***(M)***
* [ ] `/html` directory with myfirstpage.html ***(S)***

**Comment by angelabier1** [comment]
[Pull Request](https://github.com/angelabier1/TIY-Assignments/pull/13)

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki
