### ISSUE TITLE
09 -- Feeling Super, Thanks for Asking -- Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#78]
# Tasks

####Simple Tasks
* [x] Edit your wiki (please do these as your final tasks) (S)
    * [x] Edit: My thoughts on the assignment (S)
    * [x] Edit: My lightbulb moments (S)
    * [x] Edit: The things I don't understand yet (S)
####Greater Tasks
* [ ] Go through the introductory guide at http://www.htmldog.com (S)
* [ ] Read over http://www.sitepoint.com/rubyists-time-pry-irb/ and write out the code examples (M)
* [ ] Knock out those koans! Only include koans into your branch once you've completed them (M)
* [ ] Make distinct classes for BlackjackCard & PokerCard, which each inherit from a Card superclass. Reorganize your tests as well, so that each class has a matching test file that tests only the aspects of that class that are unique. (L)

####Deliverables

* [ ] Create a `/code/cards` directory with two subdirectories and two files:
        * [ ] `/blackjack`, with completed `blackjack_card_test.rb` and `blackjack_card.rb`
        * [ ] `/three_card_poker`, with completed `poker_card_test.rb` and `poker_card.rb`
        * [ ] `card.rb` and `card_test.rb` can live in `/code/cards`
* [ ] Create a `/code/koans` directory with only those koans in which you've made progress (finished, or at least started)
* [ ] Create a `/html` directory with `myfirstpage.html`
* [ ] Last but not least, make sure to solicit thumbsup from two other people, once you're finished!

**Comment by AJean144** [comment]
https://github.com/AJean144/TIY-Assignments/pull/7

**Comment by AJean144** [comment]
https://github.com/AJean144/TIY-Assignments/wiki
