### ISSUE TITLE
09 -- Feeling Super, Thanks for Asking -- Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#80]
#### Tasks
* [X] {XS} Create a new Issue with these tasks!
* [X] {XS} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [x] {S} End of lab wiki edit **(please finish this by 5 so I can use the feedback in shaping plans for tomorrow)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [X] {S} Go through the [introductory guide](http://www.htmldog.com/guides/html/beginner/) at [HTMLDOG](http://www.htmldog.com). 
* [x] {S} Read over http://www.sitepoint.com/rubyists-time-pry-irb/ and write out the code examples it gives you.
* [X] {S} Use the Terminal in your computer to:
    * [X] create a W.I.P branch of your `TIY-Assignments` repo.
    * [X] Create the files and directories as described in _Deliverables_.
    * [X] Add and commit your work.
    * [X] Push your commits to Github.
    * [X] In Github, open a PR.
* [ ] {L} Complete code assignment.
      * [ ] Make distinct classes for BlackjackCard and PokerCard, which each inherit from a Card superclass.
* [ ] Work on Koans.
* [x] {S} End of day wiki edit **(please do these as your final tasks)**
    * [x] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [x] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of the day.
* [ ] Get :+1:  :+1:

**Comment by Peterortiz82** [comment]
[Wiki Pages](https://github.com/Peterortiz82/TIY-Assignments/wiki)
