### ISSUE TITLE
10--MoERb--Andell Jean-Jacques

### ISSUE THREAD

**Issue by AJean144** [TheIronYard--Orlando/ROR--2015--SPRING#90]
# Tasks

#### Simple Tasks
* [ ] Edit your wiki (please do these as your final tasks) (S)
    * [ ] Edit: My thoughts on the assignment (S)
    * [ ] Edit: My lightbulb moments (S)
    * [ ] Edit: The things I don't understand yet (S)

#### Greater Tasks
* [ ] Ruby/HTML constructs (L)
  * [ ] Get images of every card to appear on an HTML page (M)
  * [ ] use a second pair of erb/html files to get those images to appear with your Deck & Card classes (M)
  * [ ] add a `#to_img` method on Card so that instead of writing 
`<img src="/path/to/queen/of/hearts.svg">` you can just write `<%= @queen_of_hearts.to_img %> ` (L)

#### Deliverables
* [ ] Create a `/code/cards` directory with four files:
    * [ ] `deck_display.erb` and `deck_display.html`
    * [ ] `card_display.erb` and `card_display.html`
    * [ ] Within these same folders, use the `card.rb` and `deck.rb` files to make the display work
* [ ] Last but not least, make sure to solicit thumbsup from two other people, once you're finished!

**Comment by AJean144** [comment]
https://github.com/AJean144/TIY-Assignments/pull/8

**Comment by AJean144** [comment]
https://github.com/AJean144/TIY-Assignments.wiki.git
