### ISSUE TITLE
10 -- MoERb -- Angela Bier

### ISSUE THREAD

**Issue by angelabier1** [TheIronYard--Orlando/ROR--2015--SPRING#91]
**Tasks**

* [ ] [A _WIP Issue_ in the class repo] (https://github.com/TheIronYard--Orlando/ROR--2015--SPRING/issues) titled `"10 -- MoERb -- #{YOUR NAME}"` with: ***(S)***
  * [ ] With check boxes for the tasks *and any subtasks you can identify*
  * [ ] Estimates for the **top-level** checkboxes
* [ ]  Update your `TIY-Assignments` wiki  ***(S)***
  * [ ] End of Lab *(Due by 5 pm)*: 
     * [ ] Assignment Evaluation
     * [ ] Lightbulbs
     * [ ] Things I Don’t Get Yet
  * [ ] End of Day: 
	   * [ ] Assignment Evaluation
	   * [ ] Lightbulbs
	   * [ ] Things I Don’t Get Yet
* [ ] Create a _branch_ in your `TIY-Assignments` repo _from master_ , named `feature/10 -- MoERb`  ***(XL)***
  * a series of commits after each milestone or hour (whichever comes first), with an informative commit message for each
    * [ ] an `html/` folder with matching erb and html files for:
      * printing an image of every card
      * printing all the images using Deck and Card
      * printing all the images using the new #to_img method you wrote on Card
      * printing a single hand of three card poker
      * printing and describing a single hand ("Jack high", "Pair", "Straight", etc)
      * printing hands for a player and dealer, describing each, and saying who won
* [ ] A Pull Request in your `TIY-Assignments` folder as on previous assignments ***(S)***
  * from the branch `feature/10--MoERb` (head)
  * into the `master` branch (base)
* [ ] Comments on your WIP Issue as on previous assignments ***(S)***
  * [ ] Link to Wiki
  * [ ] Link to Pull Request (in Markdown)
* [ ] * Solve at least the following problems on codewars: ***(M)***
  * http://www.codewars.com/kata/welcome-to-the-city
  * http://www.codewars.com/kata/convert-boolean-values-to-strings-yes-or-no
  * http://www.codewars.com/kata/grader

**Comment by angelabier1** [comment]
[Pull Request](https://github.com/angelabier1/TIY-Assignments/pull/14 )

**Comment by angelabier1** [comment]
https://github.com/angelabier1/TIY-Assignments/wiki
