### ISSUE TITLE
10 -- MoERb -- Joe Cursi

### ISSUE THREAD

**Issue by malkin28025** [TheIronYard--Orlando/ROR--2015--SPRING#93]
#### Tasks

* [ ] Create a new Issue WIP isuue in the class repo named appropriately()
* [ ] Estimate all the top-level tasks with _T-shirt sizes_: _S_, _M_, _L_, _XL_()
* [ ] Edit your wiki: Assigment Evaluation, _Light Bulbs_, and _Things I Don't Get Yet_()
* [ ] Create a new page in your `TIY-Assignments` repo that contains: a series of commits after each milestone or hour (whichever comes first), with an informative commit ()
* [ ] an `html/` folder with matching erb and html files for:
        * printing an image of every card
        * printing all the images using Deck and Card
        * printing all the images using the new #to_img method you wrote on Card
        * printing a single hand of three card poker
        * printing and describing a single hand ("Jack high", "Pair", "Straight", etc)
        * printing hands for a player and dealer, describing each, and saying who won
* [ ] Solve at least the following problems on codewars:
        * http://www.codewars.com/kata/welcome-to-the-city
        * http://www.codewars.com/kata/convert-boolean-values-to-strings-yes-or-no
        * http://www.codewars.com/kata/grader
* [ ] Create a new page in your `TIY-Assignments` repo()
	* [ ] description that links to your _WIP Issue_ in the class repo using _Github Flavored Markdown()
        * [ ] A Pull Request in your TIY-Assignments folder()
        * [ ] two :thumbsup: comments from peers who have reviewed your work()
* [ ] End of night wiki()
	* [ ] A Pull Request in your TIY-Assignments folder()

**Comment by malkin28025** [comment]
https://github.com/TheIronYard--Orlando/ROR--2015--SPRING/wiki
