### ISSUE TITLE
11--Middleperson Would Be More Inclusive -- Kelly Strickland

### ISSUE THREAD

**Issue by QueVee** [TheIronYard--Orlando/ROR--2015--SPRING#94]
**Tasks**

- [ ] A WIP Issue in the class repo titled "11--Middleperson Would Be More Inclusive" (m)
    - [ ] Estimates for the top-level checkboxes (xs)
- [ ] Update your TIY-Assignments repo wiki: (s)
    - [ ] Add your thoughts on today's assignment to the existing reflections page
    - [ ] Edit the lightbulbs and struggles pages
- [ ] A branch named feature/11--Middleperson Would Be More Inclusive (M)
- [ ] an /html directory with many pages (XXXL)
    - [ ] Sketch out ideas for how to organize your site
    - [ ] Read up on what Middleman can do for you
    - [ ] Sketch out what different pages in your site might look like/contain
    - [ ] Decide how fancy-looking you can reasonably expect to get in a weekend
    - [ ] Write a lot of erb/html which reflects everything you know about this stuff
- [ ] a series of commits after each milestone or hour (whichever comes first), with an informative
    commit message for each (S)
- [ ] A Pull Request (PR) (m)
- [ ] description that links to your WIP Issue in the class repo using Github Flavored Markdown (S)
- [ ] two :thumbsup: comments from peers who have reviewed your work
- [ ] Comments on your WIP Issue for the following: (S)
    - [ ] a link to your wiki (absolute URL)
    - [ ] a link to your PR using Github Flavored Markdown

**Comment by QueVee** [comment]
https://github.com/QueVee/TIY-Assignments/wiki
