### ISSUE TITLE
11--Middleperson Would Be More Inclusive--Peter Ortiz

### ISSUE THREAD

**Issue by Peterortiz82** [TheIronYard--Orlando/ROR--2015--SPRING#95]
#### Tasks
* [X] {S} Create a new Issue with these tasks!
* [X] {S} Estimate all the top-level tasks with T-shirt sizes: S, M, L, XL
* [ ] {S} Edit wiki **
    * [ ] Add your thoughts on this assignment to the _Assignment Evaluation_ page. 
    * [ ] Update _Light Bulbs_ and _Things I Don't Get Yet_ to reflect how you feel at the end of lab.
* [ ] {XL} Use the Terminal in your computer to:
    * [X] create a W.I.P branch of your `TIY-Assignments` repo.
    * [X] Sketch out ideas for how to organize your site
    * [X] Read up on what Middleman can do for you
    * [X] Sketch out what different pages in your site might look like/contain
    * [ ] Write a lot of erb/html which reflects everything you know about this stuff
    * [x] Add and commit your work.
    * [X] Push your commits to Github.
    * [x] In Github, open a PR.

**Comment by Peterortiz82** [comment]
[Wiki Page](https://github.com/Peterortiz82/TIY-Assignments/wiki)

**Comment by Peterortiz82** [comment]
Could not create a pull request. When I added my demo_site (middleman) directory my new branch, all of my css styling was gone? I could not find the path when it was in this branch. For now I created a new repository and have pushed what I have there until I can resolve the issue. 

[demo_site](https://github.com/Peterortiz82/demo_site)
